springdoc:
  swagger-ui:
    path: /userservice/docs
    url: /userservice/v3/api-docs
  api-docs:
    path: /userservice/v3/api-docs


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


